---
# tasks file for dhcp
- name: Gather Package Facts
  ansible.builtin.package_facts:
    manager: auto

- name: Install and Set Up DHCP if Not Installed
  when: "'dhcp-server' not in ansible_facts.packages"
  block:

    - name: Install DHCP Package
      ansible.builtin.dnf:
        name: dhcp-server
        state: present

    - name: Remove Default DHCP File
      ansible.builtin.file:
        path: /etc/dhcp/dhcpd.conf
        state: absent

    - name: Copy DHCP Configuration Template
      ansible.builtin.template:
        src: "dhcpd.conf.j2"
        dest: /etc/dhcp/dhcpd.conf
        owner: root
        group: root
        mode: "0644"

    - name: Restart and Enable DHCP
      ansible.builtin.service:
        name: dhcpd
        state: restarted
        enabled: true
