---
# tasks file for linuxiso
- name: Check if ISO HTTP Directory Exists
  ansible.builtin.stat:
    path: /var/www/html/{{ MENU_DISTRO }}
  register: folder_exists

- name: Create ISO HTTP Directory
  ansible.builtin.file:
    path: /var/www/html/{{ MENU_DISTRO }}
    state: directory
    mode: '0755'
    owner: root
    group: root
  when: not folder_exists.stat.exists

- name: Mount ISO read-only
  ansible.posix.mount:
    path: /var/www/html/{{ MENU_DISTRO }}
    src: '{{ ISO_DIR }}/{{ ISO_NAME }}'
    fstype: iso9660
    opts: loop
    state: mounted
  when: not folder_exists.stat.exists

- name: Adding Menu Entry {{ MENU_DISTRO }}
  ansible.builtin.blockinfile:
    path: /var/www/html/menu.ipxe
    marker: "# {{ MENU_DISTRO }}"
    block: |
      item {{ MENU_DISTRO }} Manual Install of {{ MENU_DISTRO }}
    insertbefore: "#OPTIONSEND"
  when: KICKSTART|length == 0

- name: Adding Menu Entry Custom {{ KICKSTART }}
  ansible.builtin.blockinfile:
    path: /var/www/html/menu.ipxe
    marker: '# {{ KICKSTART.split(".")[0] }}'
    block: |
      item {{ KICKSTART.split(".")[0] }} Custom Install of {{ MENU_DISTRO }} from {{ KICKSTART.split(".")[0] }}
    insertbefore: "#OPTIONSEND"
  when: KICKSTART|length != 0

- name: Adding Goto Label for {{ MENU_DISTRO }}
  ansible.builtin.blockinfile:
    path: /var/www/html/menu.ipxe
    marker: "# Goto {{ MENU_DISTRO }}"
    block: |
      :{{ MENU_DISTRO }}
      dhcp
      kernel http://{{ SERVER_IP }}/{{ MENU_DISTRO }}/images/pxeboot/vmlinuz
      initrd http://{{ SERVER_IP }}/{{ MENU_DISTRO }}/images/pxeboot/initrd.img
      boot vmlinuz initrd=initrd.img inst.stage2=http://{{ SERVER_IP }}/{{ MENU_DISTRO }} inst.lang=en_US kssendmac
    insertbefore: "#GOTOEND"
  when: KICKSTART|length == 0

- name: Adding Goto Label for {{ KICKSTART }}
  ansible.builtin.blockinfile:
    path: /var/www/html/menu.ipxe
    marker: '# Goto {{ KICKSTART.split(".")[0] }}'
    block: |
      :{{ KICKSTART.split(".")[0] }}
      dhcp
      kernel http://{{ SERVER_IP }}/{{ MENU_DISTRO }}/images/pxeboot/vmlinuz
      initrd http://{{ SERVER_IP }}/{{ MENU_DISTRO }}/images/pxeboot/initrd.img
      boot vmlinuz initrd=initrd.img ksdevice=bootif inst.lang=en_US kssendmac inst.text inst.ks=http://{{ SERVER_IP }}/ks/{{ KICKSTART }}
    insertbefore: "#GOTOEND"
  when: KICKSTART|length != 0

- name: Copy Kicstart Template for {{ KICKSTART }}
  ansible.builtin.template:
    src: "{{ KICKSTART }}.j2"
    dest: /var/www/html/ks/{{ KICKSTART }}
    owner: root
    group: root
    mode: '0644'
  when: KICKSTART|length != 0
