---
# tasks file for setupPXEServer
- name: Setup DHCP on System
  ansible.builtin.include_tasks: 1-dhcp.yml

- name: Setup TFTP on System
  ansible.builtin.include_tasks: 2-tftp.yml

- name: Setup HTTP on System
  ansible.builtin.include_tasks: 3-http.yml

- name: Setup the Linux Systems
  ansible.builtin.include_tasks: 4-linuxSystems.yml

- name: Setup the ESXi Systems
  ansible.builtin.include_tasks: 5-esxiSystems.yml
